version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/getkin/kin-openapi
    versions:
    - 0.39.0
    - 0.43.0
    - 0.44.0
    - 0.45.0
    - 0.45.1
    - 0.47.0
    - 0.49.0
    - 0.50.0
    - 0.52.0
    - 0.54.0
    - 0.55.0
